[env]
CC = "ccache clang"

[tasks.build]
path = "build"
script = "meson compile"

[tasks.build.cache]
path = "src"
target = ["build/ant"]

[tasks.reconfigure]
path = "build"
script = "meson setup --reconfigure"

[tasks.strip]
path = "build"
script = "strip ant"

[tasks.download]
script = [".github/download.sh", "open .github/artifacts"]

[tasks.run]
script = ["maid build -q", "./build/ant %{arg.1}"]

[tasks.amber]
script = "amber build .github/install/install.ab install.sh"

[tasks.setup]
script = ['meson subprojects download', 'meson setup build --wipe']

[tasks.no_jit]
script = ['meson subprojects download', 'meson setup build --wipe -Djit=false']

[tasks.asan]
script = ['meson subprojects download', 'meson setup build --wipe -Db_sanitize=address -Doptimization=0 -Db_lto=false -Dstrip=false -Db_lundef=false']

[tasks.debug]
script = [
  'meson subprojects download',
  'meson setup build --wipe --buildtype=debug -Doptimization=0 -Db_lto=false -Dstrip=false -Db_lundef=false -Dunity=off'
]

[tasks.install]
script = ["maid build -q", '''
   bash -c 'if which ant >/dev/null 2>&1; then
     dir=$(dirname "$(which ant)")
     cp ./build/ant "$dir/ant"
     ln -sf "$dir/ant" "$dir/antx"
   else
     mkdir -p ~/.ant/bin
     cp ./build/ant ~/.ant/bin/
     ln -sf ~/.ant/bin/ant ~/.ant/bin/antx
   fi'
''']
