name: Build Native Dependencies
description: Build llhttp, libuv, libsodium, mbedtls, zlib as needed

inputs:
  deps:
    description: Space-separated list of deps to build (llhttp libuv libsodium mbedtls zlib)
    required: true
  prefix:
    description: Install prefix
    required: true
  cc:
    description: C compiler
    required: true
  cxx:
    description: C++ compiler
    required: false
    default: ''
  ar:
    description: AR tool
    required: false
    default: ar
  ranlib:
    description: RANLIB tool
    required: false
    default: ranlib
  cmake_generator:
    description: CMake generator (Ninja, MinGW Makefiles, etc)
    required: false
    default: ''
  llhttp_version:
    required: true
  libuv_version:
    required: true
  libsodium_version:
    required: true
  mbedtls_version:
    required: true
  zlib_version:
    required: true

runs:
  using: composite
  steps:
    - name: Cache native deps
      id: cache
      uses: actions/cache@v4
      with:
        path: ${{ inputs.prefix }}
        key: deps-${{ runner.os }}-${{ runner.arch }}-${{ hashFiles('.github/versions.json') }}-v1

    - name: Prepare build environment
      if: steps.cache.outputs.cache-hit != 'true'
      shell: bash
      run: |
        mkdir -p ${{ inputs.prefix }}

    - name: Build llhttp
      if: steps.cache.outputs.cache-hit != 'true' && contains(inputs.deps, 'llhttp')
      shell: bash
      env:
        CFLAGS: '-Os -flto'
        AR: ${{ inputs.ar }}
        RANLIB: ${{ inputs.ranlib }}
      run: |
        git clone --depth 1 --branch release/v${{ inputs.llhttp_version }} https://github.com/nodejs/llhttp.git /tmp/llhttp
        cd /tmp/llhttp
        CMAKE_GENERATOR="${{ inputs.cmake_generator }}"
        CC=${{ inputs.cc }} CXX=${{ inputs.cxx || inputs.cc }} cmake -B build \
          ${CMAKE_GENERATOR:+-G "$CMAKE_GENERATOR"} \
          -DCMAKE_INSTALL_PREFIX=${{ inputs.prefix }} \
          -DBUILD_SHARED_LIBS=OFF -DBUILD_STATIC_LIBS=ON \
          -DCMAKE_BUILD_TYPE=MinSizeRel
        cmake --build build
        cmake --install build

    - name: Build libuv
      if: steps.cache.outputs.cache-hit != 'true' && contains(inputs.deps, 'libuv')
      shell: bash
      env:
        CFLAGS: '-Os -flto'
        AR: ${{ inputs.ar }}
        RANLIB: ${{ inputs.ranlib }}
      run: |
        git clone --depth 1 --branch v${{ inputs.libuv_version }} https://github.com/libuv/libuv.git /tmp/libuv
        cd /tmp/libuv
        CMAKE_GENERATOR="${{ inputs.cmake_generator }}"
        CC=${{ inputs.cc }} cmake -B build \
          ${CMAKE_GENERATOR:+-G "$CMAKE_GENERATOR"} \
          -DCMAKE_INSTALL_PREFIX=${{ inputs.prefix }} \
          -DBUILD_TESTING=OFF -DLIBUV_BUILD_SHARED=OFF \
          -DCMAKE_BUILD_TYPE=MinSizeRel
        cmake --build build
        cmake --install build

    - name: Build libsodium
      if: steps.cache.outputs.cache-hit != 'true' && contains(inputs.deps, 'libsodium')
      shell: bash
      run: |
        git clone --depth 1 --branch ${{ inputs.libsodium_version }}-RELEASE https://github.com/jedisct1/libsodium.git /tmp/libsodium
        cd /tmp/libsodium
        ./configure CC=${{ inputs.cc }} --prefix=${{ inputs.prefix }} --disable-shared --enable-static
        make -j$(nproc 2>/dev/null || sysctl -n hw.ncpu 2>/dev/null || echo 4)
        make install

    - name: Build mbedtls
      if: steps.cache.outputs.cache-hit != 'true' && contains(inputs.deps, 'mbedtls')
      shell: bash
      run: |
        git clone --depth 1 --branch mbedtls-${{ inputs.mbedtls_version }} --recurse-submodules https://github.com/Mbed-TLS/mbedtls.git /tmp/mbedtls
        cd /tmp/mbedtls
        CC=${{ inputs.cc }} cmake -B build \
          -DCMAKE_INSTALL_PREFIX=${{ inputs.prefix }} \
          -DENABLE_PROGRAMS=OFF -DENABLE_TESTING=OFF \
          -DCMAKE_BUILD_TYPE=Release \
          -DUSE_STATIC_MBEDTLS_LIBRARY=ON -DUSE_SHARED_MBEDTLS_LIBRARY=OFF
        cmake --build build -j$(nproc 2>/dev/null || sysctl -n hw.ncpu 2>/dev/null || echo 4)
        cmake --install build

    - name: Build zlib
      if: steps.cache.outputs.cache-hit != 'true' && contains(inputs.deps, 'zlib')
      shell: bash
      env:
        CFLAGS: '-Os -flto'
        AR: ${{ inputs.ar }}
        RANLIB: ${{ inputs.ranlib }}
      run: |
        git clone --depth 1 --branch v${{ inputs.zlib_version }} https://github.com/madler/zlib.git /tmp/zlib
        cd /tmp/zlib
        CMAKE_GENERATOR="${{ inputs.cmake_generator }}"
        CC=${{ inputs.cc }} cmake -B build \
          ${CMAKE_GENERATOR:+-G "$CMAKE_GENERATOR"} \
          -DCMAKE_INSTALL_PREFIX=${{ inputs.prefix }} \
          -DBUILD_SHARED_LIBS=OFF \
          -DCMAKE_BUILD_TYPE=MinSizeRel
        cmake --build build
        cmake --install build
        rm -f ${{ inputs.prefix }}/lib/libz.so* 2>/dev/null || true
