import { fileURLToPath } from "node:url";
import { readFileSync, writeFileSync } from "node:fs";
import type { Expr } from "../ts-nix/index.ts";

import {
  AttrSet,
  BinaryCache,
  DevShell,
  EachSystem,
  Flake,
  Import,
  Input,
  Let,
  NixFunction,
  Outputs,
  Package,
  ifElse,
  path,
  render,
} from "../ts-nix/index.ts";

interface AntInputs {
  self: Expr;
  nixpkgs: Expr;
  "flake-utils": Expr;
  "rust-overlay": Expr;
}

function llvmToolchain(pkgs: Expr) {
  const llvm = pkgs.get("llvmPackages_21");
  const bintools = ifElse(
    pkgs.get("stdenv", "hostPlatform", "isDarwin"),
    pkgs.get("darwin", "binutils-unwrapped"),
    llvm.get("bintools"),
  );

  return new AttrSet()
    .set("clang", llvm.get("clang-unwrapped", "out"))
    .set("compilerRt", llvm.get("compiler-rt"))
    .set("llvm", llvm.get("llvm"))
    .set("bintools", bintools)
    .set("stdenv", llvm.get("stdenv"));
}

function antOutputs(pkgs: Expr, self: Expr) {
  return new Let((scope) => {
    const toolchain = scope.bind(
      "toolchain",
      new Import("./packages/nix/toolchain.nix", { pkgs }),
    );

    const rustToolchain = scope.bind(
      "rustToolchain",
      pkgs
        .get("rust-bin", "fromRustupToolchainFile")
        .call(path("./src/temporal/rust-toolchain.toml")),
    );

    const rustPlatform = scope.bind(
      "rustPlatform",
      pkgs.get("makeRustPlatform").call({
        cargo: rustToolchain,
        rustc: rustToolchain,
      }),
    );

    const dirtyRevision = self.getOr("unknown", "dirtyShortRev");
    const ant = scope.bind(
      "ant",
      pkgs.get("callPackage").call(path("./packages/nix/package.nix"), {
        gitRev: self.getOr(dirtyRevision, "shortRev"),
        stdenv: toolchain.get("stdenv"),
        rustPlatform,
        rustToolchain,
      }),
    );

    const shell = new Import("./packages/nix/shell.nix", { pkgs, toolchain });

    return new Outputs(
      new Package("ant", ant).asDefault(),
      new DevShell("default", shell),
    );
  });
}

function systemOutputs(inputs: AntInputs, system: Expr) {
  return new Let((scope) => {
    const pkgs = scope.bind(
      "pkgs",
      new Import(inputs.nixpkgs, {
        system,
        overlays: [inputs["rust-overlay"].get("overlays", "default")],
      }),
    );

    return antOutputs(pkgs, inputs.self);
  });
}

function flakeOutputs(inputs: AntInputs) {
  return new EachSystem(inputs["flake-utils"], (system) =>
    systemOutputs(inputs, system),
  );
}

const nixpkgs = new Input("nixpkgs", "github:NixOS/nixpkgs/nixos-unstable");
const flakeUtils = new Input("flake-utils", "github:numtide/flake-utils");

const rustOverlay = new Input(
  "rust-overlay",
  "github:oxalica/rust-overlay",
).follows("nixpkgs", nixpkgs);

const cache = new BinaryCache(
  "https://ant.cachix.org",
  "ant.cachix.org-1:v/FbrMBfZ/rZHKZtAqM5mpLu6YKLaDF64dcLP30VTH0=",
);

const toolchainFile = new NixFunction(["pkgs"], ({ pkgs }) =>
  llvmToolchain(pkgs),
);

const flake = new Flake(
  "javascript for 🐜's, a tiny runtime with big ambitions",
)
  .inputs(nixpkgs, flakeUtils, rustOverlay)
  .cache(cache)
  .outputs(flakeOutputs);

const args = process.argv.slice(2);
if (args.some((arg) => arg !== "--check")) {
  throw new Error("Usage: ant packages/nix/generate.ts [--check]");
}

const check = args.includes("--check");
const header = "# Generated by packages/nix/generate.ts; edit the TypeScript source.\n";
  
const outputs = [
  ["../../flake.nix", flake],
  ["./toolchain.nix", toolchainFile],
] as const;

for (const [relative, value] of outputs) {
  const filename = fileURLToPath(new URL(relative, import.meta.url));
  const text = header + render(value);

  if (check) {
    if (readFileSync(filename, "utf8") !== text)  throw new Error(`Stale generated file: ${filename}`);
  } else writeFileSync(filename, text);
}
