#ifndef COMMON_H
#define COMMON_H

#define SLOTMASK ~(((ant_offset_t) ~0) >> 1)
#define CONSTMASK (~(((ant_offset_t) ~0) >> 1) >> 1)
#define ARRMASK (~(((ant_offset_t) ~0) >> 1) >> 2)
#define NONCONFIGMASK (~(((ant_offset_t) ~0) >> 1) >> 3)
#define FLAGMASK (SLOTMASK | CONSTMASK | ARRMASK | NONCONFIGMASK)

typedef enum {
  SLOT_NONE = 0,
  SLOT_PID,
  SLOT_ASYNC,
  SLOT_WITH,
  SLOT_THIS,
  SLOT_NEW_TARGET,
  SLOT_BOUND_THIS,
  SLOT_BOUND_ARGS,
  SLOT_FIELD_COUNT,
  SLOT_FIELDS,
  SLOT_STRICT,
  SLOT_CODE,
  SLOT_CODE_LEN,
  SLOT_CFUNC,
  SLOT_CORO,
  SLOT_ARROW,
  SLOT_PROTO,
  SLOT_FUNC_PROTO,
  SLOT_ASYNC_PROTO,
  SLOT_FROZEN,
  SLOT_SEALED,
  SLOT_EXTENSIBLE,
  SLOT_BUFFER,
  SLOT_TARGET_FUNC,
  SLOT_NAME,
  SLOT_MAP,
  SLOT_SET,
  SLOT_PRIMITIVE,
  SLOT_PROXY_REF,
  SLOT_BUILTIN,
  SLOT_DATA,
  SLOT_CTOR,
  SLOT_SUPER,
  SLOT_DEFAULT_CTOR,
  SLOT_DEFAULT,
  SLOT_ERROR_BRAND,
  SLOT_ERR_TYPE,
  SLOT_OBSERVABLE_SUBSCRIBER,
  SLOT_SUBSCRIPTION_OBSERVER,
  SLOT_SUBSCRIPTION_CLEANUP,
  SLOT_HOISTED_VARS,
  SLOT_HOISTED_VARS_LEN,
  SLOT_STRICT_ARGS,
  SLOT_NO_FUNC_DECLS,
  SLOT_ITER_STATE,
  SLOT_BYTECODE,
  SLOT_ENTRIES,
  SLOT_DENSE_BUF,
  SLOT_SETTLED,
  SLOT_WT_ON_MESSAGE,
  SLOT_WT_ONCE_MESSAGE,
  SLOT_WT_ON_EXIT,
  SLOT_WT_ONCE_EXIT,
  SLOT_WT_PORT_TAG,
  SLOT_WT_PORT_QUEUE,
  SLOT_WT_PORT_HEAD,
  SLOT_WT_PORT_PEER,
  SLOT_WT_PORT_CLOSED,
  SLOT_WT_PORT_STARTED,
  SLOT_WT_PORT_ON_MESSAGE,
  SLOT_WT_PORT_ONCE_MESSAGE,
  SLOT_WT_PORT_PROTO,
  SLOT_WT_ENV_STORE,
  SLOT_NAPI_EXTERNAL_ID,
  SLOT_NAPI_WRAP_ID,
  SLOT_MAX = 255
} internal_slot_t;

typedef enum {
  BUILTIN_NONE = 0,
  BUILTIN_OBJECT = 1
} builtin_fn_id_t;

#endif
