#ifndef JS_CONFIG_H
#define JS_CONFIG_H

#ifndef ANT_VERSION
#define ANT_VERSION "unknown"
#endif

#ifndef ANT_GIT_HASH
#define ANT_GIT_HASH "unknown"
#endif

#ifndef ANT_BUILD_DATE
#define ANT_BUILD_DATE "unknown"
#endif

#define JS_EXPR_MAX 20
#define JS_GC_THRESHOLD 0.75

#define GCMASK ~(((jsoff_t) ~0) >> 1)
#define CONSTMASK (~(((jsoff_t) ~0) >> 1) >> 1)
#define ARRMASK (~(((jsoff_t) ~0) >> 1) >> 2)
#define SLOTMASK (~(((jsoff_t) ~0) >> 1) >> 3)

typedef enum {
  SLOT_NONE = 0,
  SLOT_PROTO,
  SLOT_CODE,
  SLOT_SCOPE,
  SLOT_THIS,
  SLOT_NATIVE_FUNC,
  SLOT_ASYNC,
  SLOT_BOUND_THIS,
  SLOT_BOUND_ARGS,
  SLOT_TARGET_FUNC,
  SLOT_TIME,
  SLOT_MAP,
  SLOT_SET,
  SLOT_WEAKMAP,
  SLOT_WEAKSET,
  SLOT_GETTER,
  SLOT_SETTER,
  SLOT_PRIMITIVE_VALUE,
  SLOT_HANDLERS,
  SLOT_STATE,
  SLOT_VALUE,
  SLOT_SOURCE,
  SLOT_COROUTINE,
  SLOT_EXTENSIBLE,
  SLOT_SEALED,
  SLOT_FROZEN,
  SLOT_STRICT,
  SLOT_STRICT_ARGS,
  SLOT_STRICT_EVAL_SCOPE,
  SLOT_WITH_OBJECT,
  SLOT_PROXY_REF,
  SLOT_ESM_MODULE_SCOPE,
  SLOT_BUILTIN,
  SLOT_FIELDS,
  SLOT_FIELD_COUNT,
  SLOT_ITERATOR_ARR,
  SLOT_ITERATOR_IDX,
  SLOT_ITERATOR_LEN,
  SLOT_ITERATOR_STR,
  SLOT_ITERATOR_KEYS,
  SLOT_ITERATOR_VALS,
  SLOT_DESC_COMPUTED,
  SLOT_DESC_CONSTRUCTOR,
  SLOT_DESC_LENGTH,
  SLOT_DESC_PROTOTYPE,
  SLOT_MAX = 255
} internal_slot_t;

#endif
