name = "ant-manifest"
main = "src/routes.ts"

workers_dev = false
compatibility_date = "2026-05-24"

[vars]
CACHE_TTL_SECONDS = "300"

GITHUB_BRANCH = "master"
GITHUB_REPOSITORY = "theMackabu/ant"

GITHUB_RELEASE_REPOSITORY = "theMackabu/ant"
GITHUB_ACTION_REPOSITORIES = "sf-tools/ant,theMackabu/ant"

[[r2_buckets]]
binding = "DOWNLOADS"
bucket_name = "ant-downloads"

[observability]
enabled = true

[[routes]]
pattern = "manifest.antjs.org"
custom_domain = true
